### ISSUE TITLE
Not able to replicate figure 12.5

### ISSUE THREAD

**Issue by samrkuhn** [walkerke/idbr#5]
When running this code - 
`mx_pyramid_data <- get_idb(
  country = "Mexico",
  sex = c("male", "female"),
  age = 0:100,
  year = 1990:2050
) %>%
  mutate(pop = ifelse(sex == "Male", pop * -1, pop))`

it is returning the following error:
"Error in get_idb(country = "Mexico", sex = c("male", "female"), age = 0:100,  : 
  Your data request has errored.  The error message returned is error: invalid predicate: GENC" 

I'm assuming something changed within the census API, but am not able to identify what

**Comment by walkerke** [comment]
Thanks for the heads up!  Yes, something is going on with the Census API; the examples themselves on the API page are broken: https://www.census.gov/data/developers/data-sets/international-database.html.  I'll look into this.

**Comment by walkerke** [comment]
This is now fixed.  Thanks for the heads up!

**Comment by statkclee** [comment]
I've got the same error.

```
> mx_pyramid_data <- get_idb( country = "Mexico", sex = c("male", "female"), age = 0:100, year = 1990:2050 ) %>% mutate(pop = ifelse(sex == "Male", pop * -1, pop))
get_idb(country = "Mexico", sex = c("male", "female"), age = 0:100, 에서 다음과 같은 에러가 발생했습니다:
  Your data request has errored.  The error message returned is error: invalid predicate: GENC
```

**Comment by chuckleong21** [comment]
@walkerke Some IDB API changes break {idbr} 's current version.
 - `NAME`, `GENC`, and `POP` are default params now;
 - Countries parameters now use the `for=` argument and `+` signs need to be escaped in URL
 - New variables added respectively to `1year` and `5year` time series
 
 I addressed the changes above in my forked repo. Some major changes include:
 - `variables` argument now has new defaults
 - `concept` argument is now deprecated to facilitate usage of the reference table returned by `idb_variables()`
 - Use {httr2} to handle requests
 - `idb_variables()` now reads JSON directly from the API instead of scraping data from HTML
 - Redefine valid countries based on GENC standards

I would create a PR if you find these changes/ideas reasonable. This is an amazing package for demographic visualizations.
